# Information about where the book exists on the web
repository:
  url                       : https://github.com/iishiishii/example-notebooks/tree/main  # Online location of your book
  path_to_book              : fmriprep_example.ipynb  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)
  launch_buttons:
    binderhub_url: "https://play-sydney.neurodesk.org/v2/gh/iishiishii/example-notebooks/main"
