name: algolia_search_index

on:
  push:
    branches:
      - 'gh-pages'
    paths:
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.html'
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
    algolia_search_index:
        runs-on: ubuntu-latest
        steps:
        - name: Algolia crawler creation and crawl
          uses: algolia/algoliasearch-crawler-github-actions@v1.1.9
          id: algolia_crawler
          with: # mandatory parameters
            crawler-name: 'neurodesk'
            crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
            crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
            algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
            algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
            site-url: 'https://neurodesk.org/example-notebooks'
