on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

name: Build
jobs:
  build:
    name: Notebook Test
    runs-on: ubuntu-latest
    container:
      image: vnmd/neurodesktop:latest  # replace <your-docker-image> with your Docker image
      options: --user root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install nipype
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          workdir: /home/jovyan/example-notebooks