on: [push, pull_request]
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    container:
      image: vnmd/neurodesktop:latest  # replace <your-docker-image> with your Docker image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          use-docker: true
          path: ./functional_imaging
          path-output: ./functional_imaging