on: [push, pull_request]
name: Build
jobs:
  build:
    name: Notebook Test
    runs-on: ubuntu-latest
    container:
      image: vnmd/neurodesktop:latest  # replace <your-docker-image> with your Docker image
      options: --user root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          use-docker: false
          path-output: .