on: [push, pull_request]
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    container:
      image: 'Dockerfile'  # replace <your-docker-image> with your Docker image
    steps:
      - uses: actions/checkout@v3
        
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          path-output: .
          notebooks: |
            '*.ipynb'