on: [push, pull_request]
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update config.json
        run: echo "`jq '.sampleArray[0].id="5"' "*.ipynb"`" > config.json
      - name: read config.json
        run: cat config.json
    

      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
            git tag ${{ steps.semantic_release_info.outputs.git_tag }}
            
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ github.token }}
            tags: true
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
            release_name: ${{ steps.semantic_release_info.outputs.git_tag }}
            body: ${{ steps.semantic_release_info.outputs.notes }}
            draft: false
            prerelease: false