on: [push, pull_request]
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    container:
      image: syd.ocir.io/sd63xuke79z3/binderhub/jupyter-neurodesktop-proxy:20221215033354  # replace <your-docker-image> with your Docker image
    steps:
      - uses: actions/checkout@v3
        
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          path-output: .
          notebooks: |
            '*.ipynb'