name: check_broken_links

on:
  push:
    branches: ["overwrite"]
  pull_request:
    paths:
      - '**/*.ipynb'
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Create config file
        run: |
          echo ${{ steps.pages.outputs.base_url }}
          echo '{
              "replacementPatterns": [
                  {
                      "pattern": "^/",
                      "replacement": "${{ steps.pages.outputs.base_url }}/"
                  }
              ],
              "ignorePatterns": [
                  {
                      "pattern": "^https://twitter.com"
                  },
                  {
                      "pattern": "^http://localhost"
                  }
              ],
              "aliveStatusCodes": [429, 403, 200]
          }' > .github/workflows/config.json
          cat .github/workflows/config.json
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from content/en including all subfolders
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/config.json'