name: github pages

on:
  push:
    branches: ["gh-pages"]
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from content/en including all subfolders
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'