# This workflows executes new or modified example notebooks.

name: test_changed_notebooks

defaults:
  run:
    shell: bash  # To override PowerShell on Windows

on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  test_notebooks:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Test singularity and cvmfs before pushing to neurocommand
      run: 
        /bin/bash .github/workflows/setup_cvmfs.sh

    - name: Install dependencies
      shell: bash
      run: |
        pip install nbmake pytest-xdist pytest-shell jupyter-book nbconvert jupyter

    - name: Run 
      shell: bash
      run: |
        export LD_PRELOAD=
        export APPTAINER_BINDPATH=/home/runner/work/example-notebooks/example-notebooks,/tmp,/cvmfs
        export LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod
        export MPLCONFIGDIR=/home/runner/work/example-notebooks/example-notebooks/matplotlib-mpldir
        export MODULEPATH=$(find /cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/ -maxdepth 1 -mindepth 1 -type d -exec realpath {} \; | tr '\n' ':')
        find . -name '*.ipynb' -type f -execdir jupyter nbconvert --template classic --to html {} \;

    - name: Push notebooks folder to the build branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        FOLDER: notebooks # The directory where your assets are generated
        BRANCH: build # The branch name where you want to push the assets
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message
        SQUASH_HISTORY: true # If set to true, all previous commits on the target branch will be discarded. For example, if you are deploying a static site with lots of binary artifacts, this can help the repository becoming overly bloated.